### ISSUE TITLE
교수/연구실 링크 동작

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-pl/kaist-pl.github.io#7]
https://pl.kaist.ac.kr/ 저만 그런지 모르겠는데, 교수/연구실 링크들이 다 동작을 안하는 것 같습니다. 가령 "Jeehoon Kang"을 눌러도 아무데도 안가는 것 같습니다.

혹시 한번 확인해주실 수 있으실가요..?

**Comment by KihongHeo** [comment]
이름 옆에 홈페이지 아이콘을 누르면 제대로 동작을 하는데 혹시 이름을 누르셨나요?

**Comment by jeehoonkang** [comment]
확인해보니, 학내 네트워크에서는 아이콘이 잘 보이지 않는 것 같습니다 ㅎㅎ

교내 edge, firefox에선 아이콘이 안보이고

핸드폰 edge에선 아이콘이 잘 보입니다.

**Comment by KihongHeo** [comment]
아이콘을 awesome font 에서 가져와서 쓰고 있었는데. 학교에서 그쪽을 막았나봅니다. 방금 제한 풀어달라고 했고 이제 잘 동작합니다.
